### ISSUE TITLE
Why does the `cache` workflow run on macos?

### ISSUE THREAD

**Issue by valencik** [typelevel/typelevel.github.com#427]
I recently ran into CI kind of hanging up longer than usual waiting for macos runners (I think)
https://github.com/typelevel/typelevel.github.com/actions/runs/4169783105/jobs/7218103739

```
The agent pool assigned to this job has hit their MacOs concurrency limits
Requested labels: macos-latest
```

Why does the cache workflow need to run on macos as well ubuntu?

https://github.com/typelevel/typelevel.github.com/blob/development/.github/workflows/cache.yml#L15

**Comment by valencik** [comment]
I think the hang up is just that cats-effect is currently using all our macos runners.

But the question remains on whether or not we actually need to run the cache workflow, on this repo, on macOS?

**Comment by rossabaker** [comment]
It builds the development shell, and in so doing, pushes it to Cachix.  That means anyone who runs `nix develop` should be able to fetch the precise dependencies that we publish with instead of Bundler Hell.  I don't think the cache is _critical_, but I vaguely remember some tedious sassc builds when I was annoyed enough to set it up.

I do think the dev shell itself is important.  Jekyll builds have a half life more typically found in particle accelerators, and as long as we're using it, we should supply a hazmat suit.

**Comment by valencik** [comment]
Ahhhh ok, that makes perfect sense.
I agree the dev shell is important!
Thanks for the explanation :)
